table HEALTHCONNENT_PREPARED_DATA
	lineageTag: dcbbd8af-a4e0-4394-b3cd-aa5034814fd9

	measure 'Total Appointments' = DISTINCTCOUNT(HEALTHCONNENT_PREPARED_DATA[appiontment_id])
		formatString: 0
		lineageTag: c24acbc2-764a-4a36-8184-2f2075c2ae8e

	measure 'Total Patients' = DISTINCTCOUNT(HEALTHCONNENT_PREPARED_DATA[patient_id])
		formatString: 0
		lineageTag: b779c30a-53e1-422a-9825-59ca5138542a

	measure 'Total Attended' = CALCULATE([Total Appointments],HEALTHCONNENT_PREPARED_DATA[Is_attended] =1)
		formatString: 0
		lineageTag: 95811a1c-fe72-4760-aeb1-1b776426c12b

	measure 'Total No-Shows' = CALCULATE([Total Appointments],HEALTHCONNENT_PREPARED_DATA[Is_no_show]=1)
		formatString: 0
		lineageTag: b4b5ea39-070e-4ceb-838b-d6aa2b6a6c88

	measure 'Total Cancelled' = CALCULATE([Total Appointments],HEALTHCONNENT_PREPARED_DATA[Is_cancelled]=1)
		formatString: 0
		lineageTag: 7197f613-8196-4bf5-87c3-2c9cd4107894

	measure 'Attendance Rate' = DIVIDE([Total Attended],[Total Appointments],0)
		lineageTag: 96a9054f-374d-4347-9392-c0fe6f1e4731

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No-Show Rate' = DIVIDE([Total No-Shows],[Total Appointments],0)
		lineageTag: 9662dcd9-5520-4cc9-a4f4-de97ca5f5b70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cancellation Rate' = DIVIDE([Total Cancelled],[Total Appointments],0)
		lineageTag: 82a3bb45-2f0a-47bb-bae8-0f8a08a94861

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Reminder' = CALCULATE([Total Appointments],HEALTHCONNENT_PREPARED_DATA[reminder_received]=1)
		formatString: 0
		lineageTag: f934ebb3-5fcf-4cb3-af87-31608f93c38d

	measure 'Reminder Rate' = DIVIDE([Total Reminder],[Total Appointments],0)
		lineageTag: 95d32c8a-c6e5-4646-82fe-3e59b0d156a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Age' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[age])
		lineageTag: b5a79033-2f57-4443-bd8b-4fe7b8dc52cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Booking Lead Time' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[booking_lead_days])
		lineageTag: f595718f-879e-4504-8408-4725fe8d3910

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Waiting Time' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[waiting_time_minutes])
		lineageTag: 56ceb77d-5b43-45a8-be9e-36430530931a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Appiontments per Patient' = DIVIDE([Total Appointments],[Total Patients],0)
		lineageTag: be3c7ac5-0c5d-4cdd-bade-64207b229dca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Minimum Age' = MIN(HEALTHCONNENT_PREPARED_DATA[age])
		formatString: 0
		lineageTag: 06457bc6-2a6f-4292-8c4d-d0c88f97b851

	measure 'Maximum Age' = MAX(HEALTHCONNENT_PREPARED_DATA[age])
		formatString: 0
		lineageTag: a7a6d581-4baa-4884-8628-ca8c8cf3e1c4

	measure 'Median Age' = MEDIAN(HEALTHCONNENT_PREPARED_DATA[age])
		lineageTag: b91f1992-5895-4f0b-9105-62f2b122d20d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Distance' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[distance_to_clinic_km])
		lineageTag: 7eed521d-d00e-40fe-a65d-bd323c2ab638

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Previous No-Show' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[previous_no_shows])
		lineageTag: d2e895ca-9223-42cf-93fe-a31510964217

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Booking Lead Days' = AVERAGE(HEALTHCONNENT_PREPARED_DATA[booking_lead_days])
		lineageTag: 23c35a5a-ced8-4712-ade9-67877966eeeb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'High-Risk Appointment Count' = CALCULATE(DISTINCTCOUNT(HEALTHCONNENT_PREPARED_DATA[appiontment_id]),HEALTHCONNENT_PREPARED_DATA[Risk_score_group]="High Risk")
		formatString: 0
		lineageTag: 19b1b349-76b4-4535-9d5a-2fd2e93d84f3

	measure 'High-Risk No-Show' = CALCULATE(DISTINCTCOUNT(HEALTHCONNENT_PREPARED_DATA[appiontment_id]),HEALTHCONNENT_PREPARED_DATA[Risk_score_group]="High Risk",HEALTHCONNENT_PREPARED_DATA[Is_no_show]=1)
		formatString: 0
		lineageTag: efe3db9e-da7f-4aab-bfa0-370e84ad7bf9

	measure 'High-Risk No-Show Rate' = DIVIDE([High-Risk No-Show],[High-Risk Appointment Count],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3905ce53-a8dc-4f1d-85cf-8a895cc62532

	measure 'No-Reminder No-Show Rate' = CALCULATE([No-Show Rate],HEALTHCONNENT_PREPARED_DATA[reminder_sent]="No")
		lineageTag: 6b85fd9b-ea45-48aa-ad30-d6c7374280d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reminder No-Show Rate' = CALCULATE([No-Show Rate],HEALTHCONNENT_PREPARED_DATA[reminder_sent]="Yes")
		lineageTag: 651e68b3-7fea-459d-8af3-8b015def7646

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reminder Effectiveness' = [No-Reminder No-Show Rate]-[Reminder No-Show Rate]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cdc4857e-2214-4707-888e-f6005ddd0442

	measure 'No-Show Rate by Reminder' = [No-Show Rate]
		lineageTag: 23c9ee3e-b165-42c1-8452-71b21133d84f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column appiontment_id
		dataType: string
		lineageTag: 0babdc26-827e-443a-8a43-cff351d69b32
		summarizeBy: none
		sourceColumn: appiontment_id

		annotation SummarizationSetBy = Automatic

	column patient_id
		dataType: string
		lineageTag: 92fe6920-7244-4630-807b-1b4fddacc3b8
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 660b1d79-e681-49a8-b7e0-20f73560cedd
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 2e86447f-a37b-4278-9eda-d1407679d55a
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column age_group
		dataType: string
		lineageTag: e8eb2b56-3f72-4d78-b1c0-6219e2794976
		summarizeBy: none
		sourceColumn: age_group

		annotation SummarizationSetBy = Automatic

	column appointment_type
		dataType: string
		lineageTag: 97c51490-f299-4557-99b3-591c0ce3d3ee
		summarizeBy: none
		sourceColumn: appointment_type

		annotation SummarizationSetBy = Automatic

	column booking_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 55209090-471e-4df2-9f5c-23984b981b89
		summarizeBy: none
		sourceColumn: booking_date

		variation Variation
			isDefault
			relationship: 5fb530e6-0d26-4adc-98aa-93103b7d4495
			defaultHierarchy: LocalDateTable_1595cb9d-580b-4cf8-ab31-2a95c69d7123.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 30b64858-ba87-4b97-91d3-9b25e84e1ce9
		summarizeBy: none
		sourceColumn: appointment_date

		variation Variation
			isDefault
			relationship: c51056bb-e96d-4be5-91fd-2b0095da7cfd
			defaultHierarchy: LocalDateTable_1da9bede-bb55-4e10-9dc0-d3713499d64b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column appointment_day
		dataType: string
		lineageTag: e55aec97-f495-4f50-a4e9-24591d6c8ad9
		summarizeBy: none
		sourceColumn: appointment_day

		annotation SummarizationSetBy = Automatic

	column appointment_time
		dataType: string
		lineageTag: 9071bfa9-70b4-4876-b987-326e9b577738
		summarizeBy: none
		sourceColumn: appointment_time

		annotation SummarizationSetBy = Automatic

	column booking_lead_days
		dataType: int64
		formatString: 0
		lineageTag: 62e4cb96-eff2-4b36-9c88-4bdb4bde9ffb
		summarizeBy: sum
		sourceColumn: booking_lead_days

		annotation SummarizationSetBy = Automatic

	column previous_appointments
		dataType: int64
		formatString: 0
		lineageTag: f63f0520-8e17-4007-8565-302910be7674
		summarizeBy: sum
		sourceColumn: previous_appointments

		annotation SummarizationSetBy = Automatic

	column previous_no_shows
		dataType: int64
		formatString: 0
		lineageTag: ec83c8f3-d256-4e00-b0cf-0fe577f77d0c
		summarizeBy: sum
		sourceColumn: previous_no_shows

		annotation SummarizationSetBy = Automatic

	column reminder_sent
		dataType: string
		lineageTag: ae661e5e-aec0-4c5f-afc9-bc6d0d12ea3b
		summarizeBy: none
		sourceColumn: reminder_sent

		annotation SummarizationSetBy = Automatic

	column reminder_channel
		dataType: string
		lineageTag: b18ae96f-3b9a-48aa-9d0e-63c945a27128
		summarizeBy: none
		sourceColumn: reminder_channel

		annotation SummarizationSetBy = Automatic

	column distance_to_clinic_km
		dataType: double
		lineageTag: f3d2645e-2527-4b59-b2a4-c1785eb8fd46
		summarizeBy: sum
		sourceColumn: distance_to_clinic_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column waiting_time_minutes
		dataType: double
		formatString: 0
		lineageTag: 1a81488c-9ebc-4b0c-9db5-033a7c209fb5
		summarizeBy: sum
		sourceColumn: waiting_time_minutes

		annotation SummarizationSetBy = Automatic

	column appointment_outcome
		dataType: string
		lineageTag: 474e6691-474b-4d35-8092-6557b67cee2a
		summarizeBy: none
		sourceColumn: appointment_outcome

		annotation SummarizationSetBy = Automatic

	column has_previous_no_shows
		dataType: string
		lineageTag: 22ef2280-6797-47a2-8478-6563590f0fcc
		summarizeBy: none
		sourceColumn: has_previous_no_shows

		annotation SummarizationSetBy = Automatic

	column booking_lead_group
		dataType: string
		lineageTag: fce84fc6-8d30-4d43-b9f3-878c21498cd1
		summarizeBy: none
		sourceColumn: booking_lead_group

		annotation SummarizationSetBy = Automatic

	column waiting_time_group
		dataType: string
		lineageTag: 35ba6c63-8408-4879-94c0-b1aa600a02f3
		summarizeBy: none
		sourceColumn: waiting_time_group

		annotation SummarizationSetBy = Automatic

	column Is_no_show
		dataType: int64
		formatString: 0
		lineageTag: 7f2e609e-a921-4ad5-85e5-b365cfc10dd1
		summarizeBy: sum
		sourceColumn: Is_no_show

		annotation SummarizationSetBy = Automatic

	column Is_attended
		dataType: int64
		formatString: 0
		lineageTag: c761bd9b-06d6-41e5-9d85-dc79fe79d8e7
		summarizeBy: sum
		sourceColumn: Is_attended

		annotation SummarizationSetBy = Automatic

	column Is_cancelled
		dataType: int64
		formatString: 0
		lineageTag: e9555fa7-4182-4442-ab6c-1a5f0b5c3381
		summarizeBy: sum
		sourceColumn: Is_cancelled

		annotation SummarizationSetBy = Automatic

	column reminder_received
		dataType: int64
		formatString: 0
		lineageTag: 6a5234e4-dc6c-4562-9498-26be9b2ebeb3
		summarizeBy: sum
		sourceColumn: reminder_received

		annotation SummarizationSetBy = Automatic

	column Distance_group = SWITCH(TRUE(),HEALTHCONNENT_PREPARED_DATA[distance_to_clinic_km] <5, "0-5km", HEALTHCONNENT_PREPARED_DATA[distance_to_clinic_km] <=10,"6-10km", HEALTHCONNENT_PREPARED_DATA[distance_to_clinic_km] <=20,"11-20km", HEALTHCONNENT_PREPARED_DATA[distance_to_clinic_km]<=30,"21-30km", "above 30km")
		lineageTag: 51417d7a-9552-4b0d-bc47-59f4ae95c282
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Risk_score = IF([has_previous_no_shows]="Yes",2,0)+IF([booking_lead_days]>30,2,0)+IF([distance_to_clinic_km]>20,2,0)+IF([reminder_sent]="No",1,0)+IF([appointment_type]="Follow-up",1,0)
		formatString: 0
		lineageTag: e8908e76-9c5d-42f5-8cda-1d27c905d36f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Risk_score_group = SWITCH(TRUE(),[Risk_score]>=5,"High Risk", [Risk_score]>=3,"Medium Risk", "Low Risk")
		lineageTag: 0778dcda-8156-4235-8b37-a4c5f776617b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition HEALTHCONNENT_PREPARED_DATA = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\DELL\Desktop\ANALYSTS AFRICA\HEALTH CARE\HEALTHCARE_PREPARED DATA.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "HEALTHCONNENT_PREPARED_DATA", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"appiontment_id", type text}, {"patient_id", type text}, {"gender", type text}, {"age", Int64.Type}, {"age_group", type text}, {"appointment_type", type text}, {"booking_date", type date}, {"appointment_date", type date}, {"appointment_day", type text}, {"appointment_time", type text}, {"booking_lead_days", Int64.Type}, {"previous_appointments", Int64.Type}, {"previous_no_shows", Int64.Type}, {"reminder_sent", type text}, {"reminder_channel", type text}, {"distance_to_clinic_km", type number}, {"waiting_time_minutes", Int64.Type}, {"appointment_outcome", type text}, {"has_previous_no_shows", type text}, {"booking_lead_group", type text}, {"distance _group", type text}, {"waiting_time_group", type text}, {"Is_no_show", Int64.Type}, {"Is_attended", Int64.Type}, {"Is_cancelled", Int64.Type}, {"reminder_received", Int64.Type}}, "en-US"),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed column type",null,8.7,Replacer.ReplaceValue,{"distance_to_clinic_km"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",0,24,Replacer.ReplaceValue,{"waiting_time_minutes"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value1",{"distance _group"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

